index:
    path: /
    controller: App\Controller\HelloController::helloWorld

hello:
    path: /hello/{name}
    controller: App\Controller\HelloController::helloName
    defaults:
        name: "Chuck Norris"

helloTemplate:
    path: /html/hello
    controller: App\Controller\HelloController::helloTemplate

chuckNorris:
    path: /norris
    controller: App\Controller\ActionHeroes::chuckNorris

sylvesterStallone:
    path: /stallone
    controller: App\Controller\ActionHeroes::sylvesterStallone

arnoldSchwarzenegger:
    path: /arnold
    controller: App\Controller\ActionHeroes::arnoldSchwarzenegger